const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const core = require('@actions/core');
const exec = require('@actions/exec');
const github = require('@actions/github');

async function createPr(workspaceDir, repository, sourceBranch, githubToken, githubApiUrl) {
  try {
    const sourceCodeDir = path.join(workspaceDir, 'source-code');
    const fixPrBranchPrefix = 'scafix';
    const fixPrCommitMessage = 'Changes auto-generated by Veracode Fix for SCA';

    // Generate current changes diff hash
    core.info('Generating current changes diff...');
    let currentDiff = '';

    await exec.exec('git', ['--no-pager', 'diff', '--no-color', 'HEAD'], {
      cwd: sourceCodeDir,
      listeners: {
        stdout: (data) => {
          currentDiff += data.toString();
        }
      }
    });

    // Create short hash from diff
    const diffHash = crypto.createHash('sha256').update(currentDiff).digest('hex');
    const diffShortHash = diffHash.substring(0, 8);
    core.info(`Current diff short hash: ${diffShortHash}`);

    // Create new branch for Fix Pull Request
    const branchName = `${fixPrBranchPrefix}-${diffShortHash}-${sourceBranch}`;
    core.info(`Creating branch: ${branchName}`);

    await exec.exec('git', ['checkout', '-b', branchName], {
      cwd: sourceCodeDir
    });

    // Configure git user
    await exec.exec('git', ['config', 'user.name', 'Veracode SCA Fix Bot'], {
      cwd: sourceCodeDir
    });

    await exec.exec('git', ['config', 'user.email', 'sca-fix@veracode.com'], {
      cwd: sourceCodeDir
    });

    // Show status
    await exec.exec('git', ['status'], {
      cwd: sourceCodeDir
    });

    // Commit and push changes
    core.info('Committing changes...');
    await exec.exec('git', ['add', '-u'], {
      cwd: sourceCodeDir
    });

    await exec.exec('git', ['commit', '-m', fixPrCommitMessage], {
      cwd: sourceCodeDir
    });

    core.info(`Pushing branch to origin/${branchName}...`);
    await exec.exec('git', ['push', 'origin', branchName], {
      cwd: sourceCodeDir
    });

    // Create Pull Request using GitHub API (Octokit)
    core.info('Creating pull request via GitHub API...');
    const prTitle = `[Veracode Fix for SCA] ${branchName}`;
     // Check for sca-fix-report.md and use it for PR description
    let prBody = '';
    const reportPath = path.join(sourceCodeDir, 'sca-fix-report.md');
    if (fs.existsSync(reportPath)) {
      try {
        prBody = fs.readFileSync(reportPath, 'utf8');
        core.info('Loaded sca-fix-report.md for PR description');
      } catch (error) {
        core.warning(`Failed to read sca-fix-report.md: ${error.message}`);
        prBody = '## Veracode Fix for SCA\n\nAutomated dependency updates applied.';
      }
    } else {
      core.warning('sca-fix-report.md not found. Using default PR description.');
      prBody = '## Veracode Fix for SCA\n\nAutomated dependency updates applied.';
    }

    // Parse repository string (format: owner/repo)
    const [owner, repo] = repository.split('/');
    if (!owner || !repo) {
      throw new Error(`Invalid repository format. Expected 'owner/repo', got '${repository}'`);
    }

    // Initialize Octokit client
    const octokit = github.getOctokit(githubToken);

    // Create pull request using Octokit
    const prResponse = await octokit.rest.pulls.create({
      owner,
      repo,
      title: prTitle,
      body: prBody,
      head: branchName,
      base: sourceBranch
    });

    // Clean up report file after using it
    try {
      if (fs.existsSync(reportPath)) {
        fs.unlinkSync(reportPath);
        core.info('Cleaned up sca-fix-report.md');
      }
    } catch (error) {
      core.warning(`Failed to clean up sca-fix-report.md: ${error.message}`);
    }

    // Save response to file for use in upload-pr-comment step
    const responseFilePath = path.join(workspaceDir, 'github_fix_pr_post_response.json');
    fs.writeFileSync(responseFilePath, JSON.stringify(prResponse.data, null, 2));

    return { success: true, prResponse: prResponse.data };
  } catch (error) {
    throw new Error(`Failed to create pull request: ${error.message}`);
  }
}

module.exports = createPr;
